[package]
name = "ash-opinionated-abstractions"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
ash = "0.33.3"
gpu-allocator = "0.10.0"
log = "0.4.14"
vk-sync = { package = "vk-sync-fork", version = "0.2.2" }
